#! /bin/bash -e
WORK_DIR=${WORK_DIR:-`cd ${0%/*};pwd`}
DOCKER_KB_PATH=/src/knowledge
ENV=${ENV:-local}
KB_BUILDER_IMAGE=node:16
GEN_DIST_COMMAND_BUILD="npm run docs:build"

docker pull ${KB_BUILDER_IMAGE}

docker run --rm -i -v ${WORK_DIR}:${DOCKER_KB_PATH} \
  -w ${DOCKER_KB_PATH} \
  ${KB_BUILDER_IMAGE} sh -c 'npm install -D vuepress && npm run docs:build'