#! /bin/bash -e
WORK_DIR=${WORK_DIR:-`cd ${0%/*};pwd`}
DOCKER_KB_PATH=/src/knowledge
REGISTRY_HOST=${REGISTRY_HOST:-"registry.ap-southeast-1.aliyuncs.com"}
ENV=${ENV:-local}
# KB_BUILDER_IMAGE=${REGISTRY_HOST}/yhhnamespace/base-nodejs:16.20.0-local
KB_BUILDER_IMAGE=node:16
GEN_DIST_COMMAND="npm run docs:build"

# docker pull ${KB_BUILDER_IMAGE}

docker run --rm -it -p 8080:8080 -v ${WORK_DIR}:${DOCKER_KB_PATH} \
  -w ${DOCKER_KB_PATH} \
  ${KB_BUILDER_IMAGE} bash
