#! /bin/bash -e
WORK_DIR=${WORK_DIR:-`cd ${0%/*};pwd`}
DOCKER_KB_PATH=/src/knowledge
ENV=${ENV:-local}
KB_BUILDER_IMAGE=node:16.20.2
GEN_DIST_COMMAND="npm run docs:build"

docker pull ${KB_BUILDER_IMAGE}

docker run --rm -it -p 8080:8080 -v ${WORK_DIR}:${DOCKER_KB_PATH} \
  -w ${DOCKER_KB_PATH} \
  ${KB_BUILDER_IMAGE} bash


# 如果没有安装 vuepress 进入容器之后需要安装一下 npm install -D vuepress
