#! /bin/bash -e

docker stop testdist
docker rm testdist
docker run --name testdist -p 8000:80 -itd nginxwithdist

## 使用SSH传输文件/文件夹: https://blog.csdn.net/bedisdover/article/details/51622133
# 本地连接服务器： ssh root@ip
#1. 从服务器下载文件
#命令格式如下：
#
#scp <用户名>@<ssh服务器地址>:<文件路径> <本地文件名>
#
#示例，下载文件到本地桌面
#
#scp root@127.0.0.1:~/test.txt ~/Desktop/test.txt
#
#2. 上传文件到服务器
#命令格式如下：
#
#scp <本地文件名> <用户名>@<ssh服务器地址>:<上传保存路径即文件名>
# 例如：scp -r /home/user/workspace/knowledge/docs/.vuepress root@ip:/opt/vuepress
#
#这里需要注意的一点是，只能将文件上传至用户目录下。如需上传至其它目录，可先上传至用户目录，然后移动文件至指定位置。
#3. 文件夹操作
#上传/下载文件夹操作与文件操作类似，只需加入参数 -r 即可。
##
# 上传完成后登录服务器进入 /opt/vuepress 目录，执行 `docker build -t nginxwithdist .` 构建镜像
# 启动容器： docker run --name kb -p 8000:80 -itd nginxwithdist