#! /bin/bash -e

source ~/.bashrc

nvm use v16.20.0

npm install -D vuepress

yarn docs:build

docker build -t nginxwithdist .

# 检查容器是否存在
if sudo docker ps -a | grep -q "kb"; then
    docker rm -f kb
fi

docker run --name kb -p 8000:80 -itd nginxwithdist
